name: Auto Pull Request with GitHub Actions

on:
  push:
    branches-ignore:
      - "main"

jobs:
  create_pr_repo_sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create pull request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          pr_title: "feat: PLACEHOLDER TITLE"
          pr_template: ".github/PR-template.md"
          pr_reviewer: "qornainaji"
          pr_draft: true


# on:
#     pull_request:
#         branches: [ main ]

# jobs:
#     build:
#         name: Build

#         runs-on: ubuntu-latest

#         steps:
#             - name: Build the Code
#               run: |
#                 echo "Building the code"

# on:
#     push:
#         branches:
#             - main

# jobs:
#     updateAuthor:
#         runs-on: ubuntu-latest
#         steps:
#             - name: Checking out code
#               uses: actions/checkout@v2
            
#             - name: Extract git commit data
#               uses: rlespinasse/git-commit-data-action@v1.x

#             - name: Raise Pull Request

